import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Link href="/" className="text-blue-500 no-underline hover:underline">
            Home
          </Link>
          <Link
            href="/about"
            className="text-blue-500 no-underline hover:underline ml-4"
          >
            About
          </Link>
          <Link
            href="/contact"
            className="text-blue-500 no-underline hover:underline ml-4"
          >
            Contact
          </Link>
          <Link
            href="/users"
            className="text-blue-500 no-underline hover:underline ml-4"
          >
            Users
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
